CREATE TABLE IF NOT EXISTS `monitoringtable` (
  `dateOfMeasurement` datetime NOT NULL COMMENT 'Дата измерения',
  `phoneNumber` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'Идентификатор поста',
  `F0` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 0',
  `F1` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 1',
  `F2` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 2',
  `F3` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 3',
  `F4` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 4',
  `F5` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 5',
  `F6` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 6',
  `F7` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 7',
  `F8` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 8',
  `F9` float NOT NULL DEFAULT '-1000' COMMENT 'Усилие датчика 9',
  `T0` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 0',
  `T1` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 1',
  `T2` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 2',
  `T3` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 3',
  `T4` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 4',
  `nWind` float NOT NULL COMMENT 'Направление ветра',
  `vWind` float NOT NULL COMMENT 'Скорость ветра',
  `uPit` float NOT NULL COMMENT 'Напряжение питания',
  `tOkr` float NOT NULL COMMENT 'Температура внешнего датчика',
  `vlagn` float NOT NULL COMMENT 'Влажность с датчика SHT75',
  `uBat` float NOT NULL COMMENT 'Напряжение солнечной батареи',
  `zaryad` float NOT NULL COMMENT 'Заряд батареи',
  `razryad` float NOT NULL COMMENT 'Разряд батареи',
  `vectors` int(11) NOT NULL COMMENT 'Счетчик векторов',
  `cause` int(11) NOT NULL COMMENT 'Причина выхода в эфир',
  `tHumid` float NOT NULL COMMENT 'Температура с датчика SHT75',
  `uZar` float NOT NULL COMMENT 'Напряжение зарядного устройства',
  `index` int(11) NOT NULL AUTO_INCREMENT,
  `phaseA1` float NOT NULL COMMENT 'Вес фазы А 1 цепь',
  `phaseB1` float NOT NULL COMMENT 'Вес фазы В 1 цепь',
  `phaseC1` float NOT NULL COMMENT 'Вес фазы С 1 цепь',
  `tros1` float NOT NULL COMMENT 'Вес 1 троса',
  `tros2` float NOT NULL COMMENT 'Вес 2 троса',
  `phaseA2` float NOT NULL COMMENT 'Вес фазы А 2 цепь',
  `phaseB2` float NOT NULL COMMENT 'Вес фазы В 2 цепь',
  `phaseC2` float NOT NULL COMMENT 'Вес фазы С 2 цепь',
  `doorClosed` int(1) NOT NULL DEFAULT '1' COMMENT 'Дверь закрыта',
  `T_DS18S20` float NOT NULL COMMENT 'Температура внешнего датчика DS18S20',
  `t_IPTV` float NOT NULL COMMENT 'Температура с датчика ИПТВ',
  `v_IPTV` float NOT NULL COMMENT 'влажность с датчика ИПТВ',
  `T5` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 5',
  `T6` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 6',
  `T7` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 4',
  `T8` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 4',
  `T9` float NOT NULL DEFAULT '-500' COMMENT 'Температура с датчика 9',
  PRIMARY KEY (`index`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=0 ;
