DROP TABLE IF EXISTS `post_parameters`;
CREATE TABLE IF NOT EXISTS `post_parameters` (
  `phoneNumber` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'Номер телефона или другой идентификатор поста',
  `numTower` int(10) DEFAULT NULL COMMENT 'Номер опоры',
  `numLine` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'Диспетчерское наименование линии',
  `info` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'Дополнительная информация о посте',
  `periodForce` int(11) NOT NULL DEFAULT '10' COMMENT 'Период опроса при температурном окне',
  `periodTemp` int(11) NOT NULL DEFAULT '15' COMMENT 'Период опроса при тревоге по усилию',
  `periodCalendar` int(11) NOT NULL DEFAULT '25' COMMENT 'Период опроса во время гололедного периода',
  `periodNorm` int(11) NOT NULL DEFAULT '30' COMMENT 'Период опроса в норме',
  `tempMin` int(11) NOT NULL DEFAULT '-5' COMMENT 'Температурное окно -- минимум',
  `tempMax` int(11) NOT NULL DEFAULT '5' COMMENT 'Температурное окно -- максимум',
  `phaseAmaxWeight` float NOT NULL DEFAULT '200' COMMENT 'Максимальный вес на фазе А',
  `phaseBmaxWeight` float NOT NULL DEFAULT '200' COMMENT 'Максимальный вес на фазе B',
  `phaseCmaxWeight` float NOT NULL DEFAULT '200' COMMENT 'Максимальный вес на фазе C',
  `tros1MaxWeight` float NOT NULL DEFAULT '200' COMMENT 'Максимальный вес троса 1',
  `tros2MaxWeight` float NOT NULL DEFAULT '200' COMMENT 'Максимальный вес троса 2',
  `receiver1` varchar(11) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'Приемник 1',
  `receiver2` varchar(11) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `netRegion` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'Сетевой район',
  `latitude` float NOT NULL DEFAULT '0' COMMENT 'Широта',
  `longitude` float NOT NULL DEFAULT '0' COMMENT 'Долгота',
  `index` int(11) NOT NULL AUTO_INCREMENT,
  `line_direction` int(11) NOT NULL DEFAULT '0' COMMENT 'Направление линии относительно севера',
  `phaseAdryWeight` float NOT NULL DEFAULT '100' COMMENT 'Вес сухого провода на фазе А',
  `phaseBdryWeight` float NOT NULL DEFAULT '100' COMMENT 'Вес сухого провода на фазе В',
  `phaseCdryWeight` float NOT NULL DEFAULT '100' COMMENT 'Вес сухого провода на фазе С',
  `tros1dryWeight` float NOT NULL DEFAULT '50' COMMENT 'Вес сухого провода на тросе 1',
  `tros2dryWeight` float NOT NULL DEFAULT '50' COMMENT 'Вес сухого провода на тросе 2',
  `phaseAmaxFrost` float NOT NULL DEFAULT '10' COMMENT 'Максимально допустимый вес гололеда на фазе А',
  `phaseBmaxFrost` float NOT NULL DEFAULT '10' COMMENT 'Максимально допустимый вес гололеда на фазе В',
  `phaseCmaxFrost` float NOT NULL DEFAULT '10' COMMENT 'Максимально допустимый вес гололеда на фазе С',
  `tros1maxFrost` float NOT NULL DEFAULT '10' COMMENT 'Максимально допустимый вес гололеда на тросе 1',
  `tros2maxFrost` float NOT NULL DEFAULT '10' COMMENT 'Максимально допустимый вес гололеда на тросе 2',
  `phaseAmaxFrost05` float NOT NULL DEFAULT '5' COMMENT 'Порог тревоги на фазе А',
  `phaseBmaxFrost05` float NOT NULL DEFAULT '5' COMMENT 'Порог тревоги на фазе В',
  `phaseCmaxFrost05` float NOT NULL DEFAULT '5' COMMENT 'Порог тревоги на фазе С',
  `tros1maxFrost05` float NOT NULL DEFAULT '5' COMMENT 'Порог тревоги на тросе 1',
  `tros2maxFrost05` float NOT NULL DEFAULT '5' COMMENT 'Порог тревоги на тросе 2',
  `phaseAmaxFrost025` float NOT NULL DEFAULT '2' COMMENT 'Порог обнаружения гололеда на фазе А',
  `phaseBmaxFrost025` float NOT NULL DEFAULT '2' COMMENT 'Порог обнаружения гололеда на фазе В',
  `phaseCmaxFrost025` float NOT NULL DEFAULT '2' COMMENT 'Порог обнаружения гололеда на фазе С',
  `tros1maxFrost025` float NOT NULL DEFAULT '2' COMMENT 'Порог обнаружения гололеда на тросе 1',
  `tros2maxFrost025` float NOT NULL DEFAULT '2' COMMENT 'Порог обнаружения гололеда на тросе 2',
  `mainPhoneNumber` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'Номер телефона основного модема',
  `reservePhoneNumber` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'Номер телефона резервного модема',
  `callingInterval` int(11) NOT NULL DEFAULT '60' COMMENT 'Интервал дозвона',
  `lastCallingTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Время последнего сеанса связи',
  `TIME_PRIEM_ZVONKA` int(11) NOT NULL DEFAULT '5' COMMENT 'Интервал времени в течении которого контроллер ожидает прихода звонка',
  `PER_ZVONKA` int(11) NOT NULL DEFAULT '15' COMMENT 'Период между двумя последовательными сеансами  передачи  по GSM',
  `beginFrostPeriod` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Начало гололедного периода',
  `endFrostPeriod` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Конец гололедного периода',
  `periodWelding` int(11) NOT NULL DEFAULT '3' COMMENT 'Период опроса при плавке',
  `weldingMode` int(11) NOT NULL DEFAULT '0' COMMENT 'Режим плавки',
  `weldingTime` int(11) NOT NULL DEFAULT '10' COMMENT 'Время плавки',
  PRIMARY KEY (`index`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Параметры постов' AUTO_INCREMENT=0 ;
