- hosts: webservers
  ignore_errors: yes
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.phpmyadmin
